name: flutter_svg_opt
description: A command-line tool which help flutter_svg to reorder **<defs>** on right order.
version: 0.0.2
maintainer: Tokenyet (tokenyete@gmail.com)
homepage: https://github.com/Tokenyet/flutter_svg_opt

dependencies:
  args: ^2.2.0
  path: ^1.8.0
  xml: ^5.3.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.17.11
